// <auto-generated>
// Rewired Constants
// This list was generated on 4/18/2020 2:12:41 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace PBJ.Configuration.Input {
    public static partial class Actions {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "HorizontalMove")]
        public const int HorizontalMove = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "VerticalMove")]
        public const int VerticalMove = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pickup")]
        public const int Pickup = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Throw")]
        public const int Throw = 3;
    }
}
